#!/bin/bash

set -e

### Fetches and installs the latest nelson-cli from github.com

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  PLATFORM="linux-amd64"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  PLATFORM="darwin-amd64"
else
  echo "Unsupported platform: $OSTYPE"
  exit 1
fi

function fetch_from_github(){
  curl -s https://api.github.com/repos/verizon/nelson-cli/releases | grep browser_download_url | cut -d '"' -f 4 | grep $PLATFORM | head -n 2 
}

ARTIFACT_URL=$(fetch_from_github | grep -v 'sha1')
ARTIFACT_BASE="nelson-${PLATFORM}"

echo "====>> Downloading and extracting ${ARTIFACT_BASE}..."

cd /tmp
curl -sSL ${ARTIFACT_URL} -o ${ARTIFACT_BASE}.tar.gz

echo "====>> Checking shasum"
SHA_URL=$(fetch_from_github | grep 'sha1')

curl -sSL $SHA_URL -o nelson.tar.gz.sha1
SHA1=$(cat nelson.tar.gz.sha1 | awk '{print $1}')
echo "$SHA1  ${ARTIFACT_BASE}.tar.gz" > ${ARTIFACT_BASE}.tar.gz.sha1
shasum -c ${ARTIFACT_BASE}.tar.gz.sha1

echo "====>> Extracting..."

tar xzf ${ARTIFACT_BASE}.tar.gz

echo "====>> Copying nelson to /usr/local/bin..."

if [ -w /usr/local/bin ]; then
    SUDO=""
else
    SUDO="sudo "
fi
$SUDO cp nelson /usr/local/bin
