#!/bin/bash

### Fetches and installs the latest nelson-cli from our Nexus

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  PLATFORM="linux-amd64"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  PLATFORM="darwin-amd64"
else
  echo "Unsupported platform: $OSTYPE"
  exit 1
fi

NEXUS="http://nexus.oncue.verizon.net/nexus/"
PROJECT="$NEXUS/content/groups/internal/verizon/inf/slipway"
# Not everybody has a sort with a -V, so http://stackoverflow.com/a/4495368
VERSION=$(curl $PROJECT/ | sed -n -e 's#.*>\([^>]*\)/</a></td>#\1#p' | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -1)
ARTIFACT_BASE="slipway-${PLATFORM}-${VERSION}"
URI_BASE=$PROJECT/$VERSION/$ARTIFACT_BASE

echo "====>> Downloading and extracting slipway-${PLATFORM}-${VERSION}"

cd /tmp
curl -sSL ${URI_BASE}.tar.gz -o ${ARTIFACT_BASE}.tar.gz

echo "====>> Checking shasum"
curl -sSL ${URI_BASE}.tar.gz.sha1 -o ${ARTIFACT_BASE}.tar.gz.sha1
echo "  ${ARTIFACT_BASE}.tar.gz" >> ${ARTIFACT_BASE}.tar.gz.sha1
shasum -c ${ARTIFACT_BASE}.tar.gz.sha1

echo "====>> Extracting"

tar xzf ${ARTIFACT_BASE}.tar.gz

echo "====>> Copying slipway to /usr/local/bin"

if [ -w /usr/local/bin ]; then
    SUDO=""
else
    SUDO="sudo "
fi
$SUDO cp slipway /usr/local/bin
